lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-stlpreprocess_logo_light.png
    - docs/images/nf-core-stlpreprocess_logo_light.png
    - docs/images/nf-core-stlpreprocess_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-stlpreprocess_logo_light.png
    - docs/images/nf-core-stlpreprocess_logo_light.png
    - docs/images/nf-core-stlpreprocess_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Charles Plessy, Takahiro Fujita
  description: Download and pre-process genomes for the Scrambling in the Tree of
    Life project
  force: false
  is_nfcore: false
  name: LuscombeU_stlpreprocess
  org: oist
  outdir: .
  skip_features:
    - github_badges
    - igenomes
  version: 4.6.0
